Inital Lollipop changes

diff --git a/tools/opticharger b/tools/opticharger
--- a/tools/opticharger
+++ b/tools/opticharger
@@ -1,30 +1,13 @@
-#!/bin/bash
+#!/bin/sh
 #
 # Super-mega opticharger of doom
-# Shrinks apks by running pngquant or pngcrush or optipng or pngout on png images
+# Shrinks apks by running pngcrush or optipng or pngout on png images
 #
 # Point APKCERTS at the full path to a generated apkcerts.txt file, such as:
 # /home/shade/dev/sources/android-cm-eclair/out/target/product/dream_sapphire/obj/PACKAGING/target_files_intermediates/cyanogen_dream_sapphire-target_files-eng.shade/META/apkcerts.txt
 #
 # cyanogen - shade@chemlab.org
 # ChrisSoyars - me@ctso.me
-
-OUT_TARGET_HOST=$(uname -a | grep Darwin)
-if [ -z "$OUT_TARGET_HOST" ]
-then
-    OUT_TARGET_HOST=linux-x86
-else
-    OUT_TARGET_HOST=darwin-x86
-fi
-
-# out/ dir defined elsewhere
-if [ ! -z $OUT_DIR_COMMON_BASE ]; then
-	OUT_DIR=$OUT_DIR_COMMON_BASE
-else
-	OUT_DIR=$ANDROID_BUILD_TOP/out
-fi
-
-. $ANDROID_BUILD_TOP/vendor/du/tools/colors
 
 set -e
 QUIET=1
@@ -41,27 +24,24 @@ if [ "$APKCERTS" = "" ];
 then
     if [ "$TARGET_BUILD_VARIANT" = "userdebug" ]; then
        TARGET_BUILD_VARIANT="eng"
+    elif [ "$TARGET_BUILD_VARIANT" = "user" ]; then
+       TARGET_BUILD_VARIANT="eng"
     fi
 
     APKCERTS=$OUT/obj/PACKAGING/target_files_intermediates/$TARGET_PRODUCT-target_files-$TARGET_BUILD_VARIANT.$USER/META/apkcerts.txt
     if [ ! -f "$APKCERTS" ];
     then
-        echo -e $CL_RED"Set APKCERTS to the path to your apkcerts.txt file"$CL_RST
+        echo "Set APKCERTS to the path to your apkcerts.txt file"
         exit 1;
     fi
 fi
 
 if [ ! -f "$APKCERTS" ];
 then
-    echo -e $CL_RED"Invalid path to apkcerts.txt, set APKCERTS to the correct path."$CL_RST
+    echo "Invalid path to apkcerts.txt, set APKCERTS to the correct path."
 fi
 
-if [ "$(which pngquant)" != "" ];
-then
-    optimize_png () {
-        pngquant --speed 1 --force --ext .png $1 1> /dev/null 2> /dev/null
-    }
-elif [ "$(which pngcrush)" != "" ];
+if [ "$(which pngcrush)" != "" ];
 then
     optimize_png () {
         pngcrush -q ${BRUTECRUSH} $1 ${1}.out 1> /dev/null 2> /dev/null
@@ -83,26 +63,26 @@ then
         pngout $1
     }
 else
-    echo -e $CL_RED"Please install pngquant, pngcrush, optipng, or pngout"$CL_RST
+    echo "Please install pngcrush, optipng, or pngout"
     exit 1;
 fi
 
 if [ "`which aapt`" = "" ];
 then
-    echo -e $CL_RED"Please ensure aapt is in your \$PATH"$CL_RST
+    echo "Please ensure aapt is in your \$PATH"
     exit 1;
 fi
 
 if [ "`which zipalign`" = "" ];
 then
-    echo -e $CL_RED"Please ensure zipalign is in your \$PATH"$CL_RST
+    echo "Please ensure zipalign is in your \$PATH"
     exit 1;
 fi
 
 if [ -e "$1" ];
 then
     NAME=`basename $1`;
-    echo -e $CL_CYN"Optimizing"$CL_RST" $NAME...";
+    echo "Optimizing $NAME...";
 
     if [ "$2" != "" ];
     then
@@ -110,32 +90,32 @@ then
         KEY=build/target/product/security/$2.pk8
         if [ ! -f "$ANDROID_BUILD_TOP/$CERT" ];
         then
-            echo -e $CL_RED"$CERT does not exist!";$CL_RST
+            echo "$CERT does not exist!";
             exit 1;
         fi
     else
         APKINFO=`grep "name=\"$NAME\"" $APKCERTS`;
-        [ $QUIET ] || echo -e "APKINFO: $APKINFO";
+        [ $QUIET ] || echo "APKINFO: $APKINFO";
         if [ "$APKINFO" = "" ];
         then
-            echo -e $CL_RED"No apk info for $NAME";$CL_RST
+            echo "No apk info for $NAME";
             exit 1;
         fi
-        CERT=`echo -e $APKINFO | awk {'print $2'} | cut -f 2 -d "=" | tr -d "\""`;
-        KEY=`echo -e $APKINFO | awk {'print $3'} | cut -f 2 -d "=" | tr -d "\""`;
+        CERT=`echo $APKINFO | awk {'print $2'} | cut -f 2 -d "=" | tr -d "\""`;
+        KEY=`echo $APKINFO | awk {'print $3'} | cut -f 2 -d "=" | tr -d "\""`;
         if [ "$CERT" = "" ];
         then
-            echo -e $CL_RED"Unable to find certificate for $NAME"$CL_RST
+            echo "Unable to find certificate for $NAME"
             exit 1;
         fi
         if [ "$CERT" = "PRESIGNED" ];
         then
-            echo -e $CL_GRN"$NAME is presigned, skipping"$CL_RST
+            echo "$NAME is presigned, skipping"
             exit 1;
         fi
     fi
 
-    [ $QUIET ] || echo -e $CL_YLW"Certificate:"$CL_RST" $CERT";
+    [ $QUIET ] || echo "Certificate: $CERT";
 
     [ -d $TMPDIR/$NAME ] && rm -rf $TMPDIR/$NAME
     mkdir -p $TMPDIR/$NAME
@@ -144,19 +124,19 @@ then
     unzip -q $BASE/$1
     for x in `find . -name "*.png" | grep -v "\.9.png$" | tr "\n" " "`
     do
-        [ $QUIET ] || echo -e $CL_GRN"Crushing $x"$CL_RST
+        [ $QUIET ] || echo "Crushing $x"
         optimize_png $x
     done
     cp $BASE/$1 $BASE/$1.old
 
-    [ $QUIET ] || echo -e $CL_GRN"Repacking apk.."$CL_RST
+    [ $QUIET ] || echo "Repacking apk.."
     aapt p -0 .dat -0 .dict -0 .arsc -F $NAME .
+    
+    [ $QUIET ] || echo "Resigning with cert: `echo $CERT`"
 
-    [ $QUIET ] || echo -e $CL_YLW"Resigning with cert: `echo -e $CERT`"$CL_RST
-
-    [ $QUIET ] || echo -e java -jar $OUT_DIR/host/$OUT_TARGET_HOST/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
-    java -jar $OUT_DIR/host/$OUT_TARGET_HOST/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
-    [ $QUIET ] || echo -e $CL_GRN"Zipalign.."$CL_RST
+    [ $QUIET ] || echo java -jar $ANDROID_HOST_OUT/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
+    java -jar $ANDROID_HOST_OUT/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
+    [ $QUIET ] || echo "Zipalign.."
     zipalign -f 4 signed_$NAME $BASE/$1
     if [ ! $QUIET ]; then
         ls -l $BASE/$1.old
@@ -164,5 +144,6 @@ then
     fi
     rm $BASE/$1.old
 else
-    echo -e "Usage: $0 [apk file]"
+    echo "Usage: $0 [apk file]"
 fi
+
diff --git a/tools/squisher b/tools/squisher
--- a/tools/squisher
+++ b/tools/squisher
@@ -1,11 +1,8 @@
-#!/bin/bash
+#!/bin/sh
 #
 # Squish a CM otapackage for distribution
-#
 # cyanogen
-# AOKP
-
-. $ANDROID_BUILD_TOP/vendor/du/tools/colors
+#
 
 OUT_TARGET_HOST=`uname -a | grep Darwin`
 if [ -z "$OUT_TARGET_HOST" ]
@@ -16,83 +13,53 @@ then
    SED=sed
 else
    OUT_TARGET_HOST=darwin-x86
-   MD5="md5 -r "
+   MD5=md5
    XARGS="xargs -n 1 -P `sysctl hw.ncpu | awk '{print $2}'`"
    SED=gsed
 fi
 
 if [ -z "$OUT" -o ! -d "$OUT" ]; then
-	echo -e "ERROR: $0 only works with a full build environment. $OUT should exist."
-	exit 1
-fi
-
-# out/ dir defined elsewhere
-if [ ! -z $OUT_DIR_COMMON_BASE ]; then
-        OUT_DIR=$OUT_DIR_COMMON_BASE
-else
-        OUT_DIR=$ANDROID_BUILD_TOP/out
+    echo "ERROR: $0 only works with a full build environment. $OUT should exist."
+    exit 1
 fi
 
 if [ "$TARGET_BUILD_TYPE" = "debug" ]; then
     OTAPACKAGE=$OUT/${TARGET_PRODUCT}_debug-ota-$TARGET_BUILD_VARIANT.$USER.zip
 elif [ "$TARGET_BUILD_VARIANT" = "userdebug" ]; then
     OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-eng.$USER.zip
+elif [ "$TARGET_BUILD_VARIANT" = "user" ]; then
+    OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-eng.$USER.zip
 else
     OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$USER.zip
 fi
 if [ ! -f "$OTAPACKAGE" ]; then
-	echo -e "$OTAPACKAGE doesn't exist!";
-	exit 1
+    echo "$OTAPACKAGE doesn't exist!";
+    exit 1
 fi
 
 OPTICHARGER=$ANDROID_BUILD_TOP/vendor/du/tools/opticharger
 QUIET=-q
 DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
-
-
-# Some products want a squashfs for xbin for space
-case "$TARGET_PRODUCT" in
-	cyanogen_dream_sapphire) WANT_SQUASHFS=1 ;;
-	*) WANT_SQUASHFS=0 ;;
-esac
-
-if [ "$WANT_SQUASHFS" -eq 1 ]; then
-	fatal=0
-	MKSQUASHFS_VER_REQ=4
-	if type mksquashfs >/dev/null 2>&1; then
-		if mksquashfs -version | grep -q "version $MKSQUASHFS_VER_REQ"; then :; else
-			echo -e
-			echo -e $CL_RED"ERROR: mksquashfs must be at least version $MKSQUASHFS_VER_REQ for this build."$CL_RST
-			fatal=1
-		fi
-	else
-		echo -e
-		echo -e $CL_RED"ERROR: $TARGET_PRODUCT requires mksquashfs."$CL_RST
-		fatal=1
-	fi
-
-	if [ "$fatal" -ne 0 ]; then
-		echo -e
-		echo -e $CL_YLW"       Unoptimized package is still available at"
-		echo -e "         $OTAPACKAGE"$CL_RST
-		exit $fatal
-	fi
-fi
+DELETE_MEDIA="*.qmg"
+DELETE_APKS="LiveWallpapers.apk SpeechRecorder.apk VideoEditor.apk HoloSpiralWallpaper.apk MagicSmokeWallpapers.apk NoiseField.apk Galaxy4.apk OpenWnn.apk PinyinIME.apk"
+DELETE_PRIV_APKS="VoiceDialer.apk"
+DELETE_GALLERY="Gallery2.apk"
+DELETE_FONTS="MTLmr3m.ttf"
 
 REPACK=$OUT/repack.d
-echo -e $CL_RED"Sanitizing environment..."$CL_RST
+printf "Sanitizing environment..."
 rm -rf $REPACK
 mkdir -p $REPACK
-echo -e
+echo
 
 
 # Unpack the otapackage and opticharge all apks
 mkdir $REPACK/ota
 (
 cd $REPACK/ota
-echo -e $CL_RED"Unpacking $OTAPACKAGE..."$CL_RST
+printf "Unpacking $OTAPACKAGE..."
 unzip $QUIET $OTAPACKAGE
-echo -e
+echo
 
 # Move all apks to the same directory so xargs can
 # use also with framework-res.apk. This allow process
@@ -101,53 +68,25 @@ mkdir -p $REPACK/parallel
 cd $REPACK/parallel
 cp $REPACK/ota/system/framework/framework-res.apk .
 cp $REPACK/ota/system/app/*.apk .
+for f in $REPACK/ota/system/priv-app/*.apk; do
+    cp $f ./priv-app-$(basename $f)
+done
+
 
 # Do optimization in parallel
 find ./ -name \*.apk | $XARGS $OPTICHARGER
 
 # Move optimized apks to repack directory
 mv -f $REPACK/parallel/framework-res.apk $REPACK/ota/system/framework/framework-res.apk
+for f in $REPACK/parallel/priv-app*.apk; do
+    mv $f $REPACK/ota/system/priv-app/$(basename $f | cut -d'-' -f3)
+done
 mv -f $REPACK/parallel/*.apk $REPACK/ota/system/app/
-
-# Optimize /priv-app/
-cp $REPACK/ota/system/priv-app/*.apk .
-find ./ -name \*.apk | $XARGS $OPTICHARGER
-mv -f $REPACK/parallel/*.apk $REPACK/ota/system/priv-app/
 
 # Return to directory
 cd $REPACK/ota
 rm -rf $REPACK/parallel
 )
-
-
-if [ "$WANT_SQUASHFS" -eq 1 ]; then
-	squash_opts="-force-uid 1000 -force-gid 1000 -no-progress -noappend -no-exports -no-recovery"
-	updater=$REPACK/ota/META-INF/com/google/android/updater-script
-
-	# Relocate su
-	cp -a $REPACK/ota/system/xbin $REPACK/_xbin/
-	rm -f $REPACK/_xbin/su $REPACK/ota/system/bin/su
-	mv $REPACK/ota/system/xbin/su $REPACK/ota/system/bin/su
-	chmod -R 555 $REPACK/_xbin/*
-
-	# Create symlinks for su and busybox (since updater-script can't work on the squashfs filesystem).
-	# Forgive me for the regex hell here.
-	ln -s ../bin/su $REPACK/_xbin/su
-	for link in `sed -n -e's/,//g' -e'/symlink(.*busybox/,/xbin.*);/p' $updater | tr '"' '\n' | sed -n -e'\,/system/xbin/,s,/system/xbin/,,p'`
-	do
-		ln -s busybox $REPACK/_xbin/$link
-	done
-
-	# Create the squashfs with new and improved symlinkage!
-	mksquashfs $REPACK/_xbin/* $REPACK/_xbin.sqf $squash_opts
-	rm -rf $REPACK/ota/system/xbin/*
-	mv $REPACK/_xbin.sqf $REPACK/ota/system/xbin/xbin.sqf
-	chmod 444 $REPACK/ota/system/xbin/xbin.sqf
-
-	# Remove xbin stuff and fix up updater-script
-	$SED -i -e's,system/xbin/su,system/bin/su,g' -e'/xbin/d' $updater
-fi
-
 
 # Fix build.prop
 $SED -i \
@@ -157,65 +96,84 @@ $SED -i \
 
 
 # Delete unnecessary binaries
-( cd $REPACK/ota/system/bin; echo -e $DELETE_BINS | xargs rm -f; )
+( cd $REPACK/ota/system/bin; echo $DELETE_BINS | xargs rm -f; )
 
-# Delete leftover wireless driver
-# rm -rf $REPACK/ota/system/lib/modules/*/kernel/drivers/net
+# Delete Offline charging mode files
+( cd $REPACK/ota/system/media; echo $DELETE_MEDIA | xargs rm -f; )
+
+# Delete Home Apk's
+( cd $REPACK/ota/system/app; echo $DELETE_APKS | xargs rm -f; )
+
+# Delete priv-app Apk's
+( cd $REPACK/ota/system/priv-app; echo $DELETE_PRIV_APKS | xargs rm -f; )
+
+# No need for modem.bin
+rm -f $REPACK/ota/modem.bin
+
+# No need for media/video
+rm -rf $REPACK/ota/system/media/video
+
+# Delete Unnecessary Fonts
+( cd $REPACK/ota/system/fonts; echo $DELETE_FONTS | xargs rm -f; )
+
+# Delete compiled fonts
+#rm -rf $REPACK/ota/system/fonts
+
+#make dir for fonts again
+#mkdir $REPACK/ota/system/fonts
+
+# Add precompiled fonts
+#mv -f $REPACK/ota/system/sfont/*.ttf $REPACK/ota/system/fonts/
+
+# No need for tts
+rm -rf $REPACK/ota/system/tts
+
+# No need for srec
+rm -rf $REPACK/ota/system/usr/srec
 
 # No need for recovery
 rm -rf $REPACK/ota/recovery
+rm -rf $REPACK/ota/system/etc/recovery-resource.dat
 
 # Strip modules
 [ -d $REPACK/ota/system/lib/modules ] && \
 	find $REPACK/ota/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded
 
-# Determine what to name the new signed package
+# Delete Gallery2 for 5MP cameras
+CAMERARESOLUTION=`sed -n -e'/ro\.camera\.res/s/^.*=//p' $REPACK/ota/system/build.prop`
+#if [ "$CAMERARESOLUTION" = "5MP" ];then
+#   rm -f $REPACK/ota/system/app/Gallery2.apk
+#fi
 
-#MODVERSION=`sed -n -e'/ro\.modversion/s/^.*=//p' $REPACK/ota/system/build.prop`
-VERSION=`sed -n -e'/ro.du.version/s/^.*=//p' $REPACK/ota/system/build.prop`
-MODVERSION="$VERSION"
+# Determine what to name the new signed package
+MODVERSION=`sed -n -e'/ro\.modversion/s/^.*=//p' $REPACK/ota/system/build.prop`
 OUTFILE=$OUT/$MODVERSION.zip
+echo MODVERSION: $MODVERSION
 
 # Pack it up and sign
-echo -e $CL_RED"Zipping package..."$CL_RST
+printf "Zipping package..."
 ( cd $REPACK/ota; zip $QUIET -r $REPACK/update.zip . )
-echo -e
-echo -e $CL_RED"Signing package..."$CL_RST
+echo
+printf "Signing package..."
 SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
 java -Xmx1024m \
-	-jar $OUT_DIR/host/$OUT_TARGET_HOST/framework/signapk.jar \
+	-jar $OUT/../../../host/$OUT_TARGET_HOST/framework/signapk.jar \
 	-w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
 	$REPACK/update.zip $OUTFILE
-echo -e
-echo -e $CL_RED"Cleaning up..."$CL_RST
+echo
+printf "Cleaning up..."
 rm -rf $REPACK
-echo -e
+echo
 
 # Create a md5 checksum image of the repacked package
 (
 img=`basename $OUTFILE`
 cd `dirname $OUTFILE`
 $MD5 $img >$img.md5sum
-ZIPSIZE=`ls -lah $OUTFILE | awk '{ print $5}' `
-echo -e
-echo -e
-echo -e
-echo -e $CL_RED"                       8888888b.    888     888                                    " $CL_RST
-echo -e $CL_RED"                       888  Y88b    888     888                                    " $CL_RST
-echo -e $CL_RED"                       888    888   888     888                                    " $CL_RST
-echo -e $CL_RED"                       888    888   888     888                                    " $CL_RST
-echo -e $CL_RED"                       888    888   888     888                                    " $CL_RST
-echo -e $CL_RED"                       888    888   888     888                                    " $CL_RST
-echo -e $CL_RED"                       888  .d88P   Y88b. .d88P                                    " $CL_RST
-echo -e $CL_RED"                       8888888P      Y888888PY                                     " $CL_RST
-echo -e
-echo -e
-echo -e $CL_RED"====================== Dirty Unicorns complete ====================================="$CL_RST
-echo -e $CL_RED"| ZIP:"$CL_RED" $OUTFILE                                                            "$CL_RST
-echo -e $CL_RED"| MD5:"$CL_RED" $(cat $img.md5sum | awk '{ print $1 }')                             "$CL_RST
-echo -e $CL_RED"| SIZE:"$CL_RED" $ZIPSIZE                                                           "$CL_RST
-echo -e $CL_RED"======================== Now flash that shit ======================================="$CL_RST
-echo -e
+echo
+echo "Package complete: $OUTFILE"
+cat $img.md5sum
+echo
 )
 
 exit 0
